### ISSUE TITLE
Cannot start teleporter

### ISSUE THREAD

**Issue by Dromaeosaurs** [RuneFox237/RoR2Mod-TeleporterTurrets#2]
When I press interaction key, a gunner turret only teleports to the teleporter's location, no boss spawns, cannot progress further etc.
Edit: Fixed with 1.0.3 update

**Comment by Chinoman10** [comment]
Why did you close this issue @Dromaeosaurs ?
It seems to be happening still (or maybe it's a regression, but I'm not sure a new release was developed since).
